BEGIN;

ALTER TABLE public.contas_fixas
  ADD COLUMN encerrada_a_partir_da_ocorrencia INTEGER;

UPDATE public.contas_fixas
SET encerrada_a_partir_da_ocorrencia = 1
WHERE status IN ('concluido', 'cancelado')
  AND encerrada_a_partir_da_ocorrencia IS NULL;

ALTER TABLE public.contas_fixas
  DROP CONSTRAINT contas_fixas_lifecycle_shape_check,
  ADD CONSTRAINT contas_fixas_lifecycle_shape_check
    CHECK (
      (
        status = 'ativo'
        AND encerrada_em IS NULL
        AND encerrada_por IS NULL
        AND encerrada_a_partir_da_ocorrencia IS NULL
      )
      OR (
        status IN ('concluido', 'cancelado')
        AND encerrada_em IS NOT NULL
        AND encerrada_a_partir_da_ocorrencia >= 1
      )
    )
    NOT VALID;

ALTER TABLE public.contas_fixas
  VALIDATE CONSTRAINT contas_fixas_lifecycle_shape_check;

CREATE TABLE public.contas_fixas_excecoes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  family_id UUID NOT NULL,
  conta_fixa_id BIGINT NOT NULL,
  ocorrencia INTEGER NOT NULL CHECK (ocorrencia >= 1),
  acao TEXT NOT NULL DEFAULT 'ignorar' CHECK (acao = 'ignorar'),
  created_by UUID NOT NULL REFERENCES auth.users (id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  CONSTRAINT contas_fixas_excecoes_family_master_fkey
    FOREIGN KEY (family_id, conta_fixa_id)
    REFERENCES public.contas_fixas (family_id, id)
    ON DELETE RESTRICT,
  CONSTRAINT contas_fixas_excecoes_occurrence_key
    UNIQUE (family_id, conta_fixa_id, ocorrencia)
);

ALTER TABLE public.contas_fixas_excecoes ENABLE ROW LEVEL SECURITY;

CREATE POLICY contas_fixas_excecoes_select_family
  ON public.contas_fixas_excecoes
  FOR SELECT
  TO authenticated
  USING (family_id = public.get_my_family_id());

REVOKE ALL ON TABLE public.contas_fixas_excecoes FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public.contas_fixas_excecoes TO authenticated, service_role;
GRANT ALL ON TABLE public.contas_fixas_excecoes TO service_role;
REVOKE ALL ON SEQUENCE public.contas_fixas_excecoes_id_seq FROM PUBLIC, anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.contas_fixas_excecoes_id_seq TO service_role;

CREATE OR REPLACE FUNCTION public.protect_fixed_recurrence_lifecycle()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    IF current_user NOT IN ('postgres', 'service_role', 'supabase_admin') THEN
      RAISE EXCEPTION 'Recorrências devem ser encerradas, não excluídas.'
        USING ERRCODE = 'P0001';
    END IF;

    RETURN OLD;
  END IF;

  IF current_user NOT IN ('postgres', 'service_role', 'supabase_admin') THEN
    IF TG_OP = 'INSERT' THEN
      IF NEW.status <> 'ativo'
         OR NEW.encerrada_em IS NOT NULL
         OR NEW.encerrada_por IS NOT NULL
         OR NEW.encerrada_a_partir_da_ocorrencia IS NOT NULL THEN
        RAISE EXCEPTION 'Uma recorrência nova deve iniciar ativa.'
          USING ERRCODE = 'P0001';
      END IF;
    ELSIF NEW.status IS DISTINCT FROM OLD.status
       OR NEW.encerrada_em IS DISTINCT FROM OLD.encerrada_em
       OR NEW.encerrada_por IS DISTINCT FROM OLD.encerrada_por
       OR NEW.encerrada_a_partir_da_ocorrencia IS DISTINCT FROM OLD.encerrada_a_partir_da_ocorrencia THEN
      RAISE EXCEPTION 'O ciclo de vida da recorrência só pode ser alterado pelo comando de encerramento.'
        USING ERRCODE = 'P0001';
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER protect_contas_fixas_lifecycle ON public.contas_fixas;
CREATE TRIGGER protect_contas_fixas_lifecycle
  BEFORE INSERT OR UPDATE OF status, encerrada_em, encerrada_por, encerrada_a_partir_da_ocorrencia
  ON public.contas_fixas
  FOR EACH ROW
  EXECUTE FUNCTION public.protect_fixed_recurrence_lifecycle();

CREATE OR REPLACE FUNCTION public.require_active_fixed_recurrence()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_config public.contas_fixas%ROWTYPE;
  v_ocorrencia INTEGER;
  v_competencia TEXT;
  v_initial_date DATE;
  v_current_date DATE;
BEGIN
  IF NEW.conta_fixa_id IS NULL THEN
    RETURN NEW;
  END IF;

  IF TG_OP = 'UPDATE'
     AND NEW.conta_fixa_id IS NOT DISTINCT FROM OLD.conta_fixa_id THEN
    RETURN NEW;
  END IF;

  SELECT *
  INTO v_config
  FROM public.contas_fixas
  WHERE family_id = NEW.family_id
    AND id = NEW.conta_fixa_id;

  IF NOT FOUND THEN
    RETURN NEW;
  END IF;

  IF TG_TABLE_NAME = 'cartoes' THEN
    v_ocorrencia := NULLIF(to_jsonb(NEW) ->> 'conta_fixa_parcela', '')::INTEGER;
  ELSIF TG_TABLE_NAME = 'receitas' THEN
    v_competencia := to_jsonb(NEW) ->> 'competencia';
    v_initial_date := to_date('01/' || v_config.competencia_inicial, 'DD/MM/YYYY');
    v_current_date := to_date('01/' || v_competencia, 'DD/MM/YYYY');
    v_ocorrencia := (
      (EXTRACT(YEAR FROM v_current_date)::INTEGER - EXTRACT(YEAR FROM v_initial_date)::INTEGER) * 12
      + EXTRACT(MONTH FROM v_current_date)::INTEGER
      - EXTRACT(MONTH FROM v_initial_date)::INTEGER
      + 1
    );
  ELSE
    v_ocorrencia := NULLIF(to_jsonb(NEW) ->> 'parcela_atual', '')::INTEGER;
  END IF;

  IF v_ocorrencia IS NULL OR v_ocorrencia < 1 THEN
    RAISE EXCEPTION 'Não foi possível determinar a ocorrência da recorrência.'
      USING ERRCODE = '22023';
  END IF;

  IF v_config.status <> 'ativo'
     AND v_ocorrencia >= COALESCE(v_config.encerrada_a_partir_da_ocorrencia, 1) THEN
    RAISE EXCEPTION 'A ocorrência está fora do período ativo da recorrência.'
      USING ERRCODE = '55000';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.contas_fixas_excecoes
    WHERE family_id = NEW.family_id
      AND conta_fixa_id = NEW.conta_fixa_id
      AND ocorrencia = v_ocorrencia
      AND acao = 'ignorar'
  ) THEN
    RAISE EXCEPTION 'A ocorrência foi ignorada e não pode ser materializada.'
      USING ERRCODE = '55000';
  END IF;

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.ignorar_ocorrencia_conta_fixa(
  p_conta_fixa_id BIGINT,
  p_ocorrencia INTEGER
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_user_id UUID := auth.uid();
  v_family_id UUID := public.get_my_family_id();
  v_config public.contas_fixas%ROWTYPE;
  v_exception public.contas_fixas_excecoes%ROWTYPE;
BEGIN
  IF v_user_id IS NULL OR v_family_id IS NULL THEN
    RAISE EXCEPTION 'Sessão autenticada e família são obrigatórias.'
      USING ERRCODE = '42501';
  END IF;

  IF p_ocorrencia IS NULL OR p_ocorrencia < 1 THEN
    RAISE EXCEPTION 'Número de ocorrência inválido para a recorrência.'
      USING ERRCODE = '22023';
  END IF;

  SELECT *
  INTO v_config
  FROM public.contas_fixas
  WHERE family_id = v_family_id
    AND id = p_conta_fixa_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'A recorrência informada não pertence à família autenticada.'
      USING ERRCODE = '23503';
  END IF;

  IF v_config.user_id <> v_user_id AND NOT public.is_my_family_admin() THEN
    RAISE EXCEPTION 'Apenas o responsável ou titular da família pode alterar a recorrência.'
      USING ERRCODE = '42501';
  END IF;

  IF v_config.total_parcelas IS NOT NULL
     AND v_config.total_parcelas > 0
     AND p_ocorrencia > v_config.total_parcelas THEN
    RAISE EXCEPTION 'Número de ocorrência inválido para a recorrência.'
      USING ERRCODE = '22023';
  END IF;

  IF v_config.status <> 'ativo'
     AND p_ocorrencia >= COALESCE(v_config.encerrada_a_partir_da_ocorrencia, 1) THEN
    RAISE EXCEPTION 'A ocorrência já está fora do período ativo da recorrência.'
      USING ERRCODE = '55000';
  END IF;

  INSERT INTO public.contas_fixas_excecoes (
    family_id, conta_fixa_id, ocorrencia, acao, created_by
  ) VALUES (
    v_family_id, v_config.id, p_ocorrencia, 'ignorar', v_user_id
  )
  ON CONFLICT (family_id, conta_fixa_id, ocorrencia)
  DO UPDATE SET acao = EXCLUDED.acao
  RETURNING * INTO v_exception;

  RETURN jsonb_build_object(
    'id', v_exception.id,
    'conta_fixa_id', v_exception.conta_fixa_id,
    'ocorrencia', v_exception.ocorrencia,
    'acao', v_exception.acao
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.encerrar_conta_fixa_desde(
  p_conta_fixa_id BIGINT,
  p_ocorrencia INTEGER,
  p_status TEXT DEFAULT 'cancelado'
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_user_id UUID := auth.uid();
  v_family_id UUID := public.get_my_family_id();
  v_status TEXT := lower(btrim(COALESCE(p_status, '')));
  v_config public.contas_fixas%ROWTYPE;
BEGIN
  IF v_user_id IS NULL OR v_family_id IS NULL THEN
    RAISE EXCEPTION 'Sessão autenticada e família são obrigatórias.'
      USING ERRCODE = '42501';
  END IF;

  IF p_ocorrencia IS NULL OR p_ocorrencia < 1 THEN
    RAISE EXCEPTION 'Número de ocorrência inválido para o encerramento.'
      USING ERRCODE = '22023';
  END IF;

  IF v_status NOT IN ('concluido', 'cancelado') THEN
    RAISE EXCEPTION 'Estado final inválido para a recorrência.'
      USING ERRCODE = '22023';
  END IF;

  SELECT *
  INTO v_config
  FROM public.contas_fixas
  WHERE family_id = v_family_id
    AND id = p_conta_fixa_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'A recorrência informada não pertence à família autenticada.'
      USING ERRCODE = '23503';
  END IF;

  IF v_config.user_id <> v_user_id AND NOT public.is_my_family_admin() THEN
    RAISE EXCEPTION 'Apenas o responsável ou titular da família pode encerrar a recorrência.'
      USING ERRCODE = '42501';
  END IF;

  IF v_config.total_parcelas IS NOT NULL
     AND v_config.total_parcelas > 0
     AND p_ocorrencia > v_config.total_parcelas THEN
    RAISE EXCEPTION 'Número de ocorrência inválido para o encerramento.'
      USING ERRCODE = '22023';
  END IF;

  IF v_config.status = v_status
     AND v_config.encerrada_a_partir_da_ocorrencia = p_ocorrencia THEN
    RETURN jsonb_build_object(
      'id', v_config.id,
      'status', v_config.status,
      'encerrada_a_partir_da_ocorrencia', v_config.encerrada_a_partir_da_ocorrencia,
      'encerrada_em', v_config.encerrada_em
    );
  END IF;

  IF v_config.status <> 'ativo' THEN
    RAISE EXCEPTION 'Uma recorrência encerrada não pode mudar seu ponto de corte.'
      USING ERRCODE = '55000';
  END IF;

  UPDATE public.contas_fixas
  SET status = v_status,
      encerrada_em = clock_timestamp(),
      encerrada_por = v_user_id,
      encerrada_a_partir_da_ocorrencia = p_ocorrencia,
      updated_at = clock_timestamp()
  WHERE id = v_config.id
  RETURNING * INTO v_config;

  RETURN jsonb_build_object(
    'id', v_config.id,
    'status', v_config.status,
    'encerrada_a_partir_da_ocorrencia', v_config.encerrada_a_partir_da_ocorrencia,
    'encerrada_em', v_config.encerrada_em
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.encerrar_conta_fixa(
  p_conta_fixa_id BIGINT,
  p_status TEXT DEFAULT 'cancelado'
)
RETURNS JSONB
LANGUAGE sql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
  SELECT public.encerrar_conta_fixa_desde(p_conta_fixa_id, 1, p_status);
$$;

REVOKE ALL ON FUNCTION public.ignorar_ocorrencia_conta_fixa(BIGINT, INTEGER) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.encerrar_conta_fixa_desde(BIGINT, INTEGER, TEXT) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.encerrar_conta_fixa(BIGINT, TEXT) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.ignorar_ocorrencia_conta_fixa(BIGINT, INTEGER) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.encerrar_conta_fixa_desde(BIGINT, INTEGER, TEXT) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.encerrar_conta_fixa(BIGINT, TEXT) TO authenticated, service_role;

COMMIT;
