-- Migration: Adding Loans Module
-- Date: 2026-03-29
-- Description: Creates the 'emprestimos' table for long-term debt tracking and adds the calculation fields for anticipation simulations.

-- 1. Create Emprestimos table
CREATE TABLE IF NOT EXISTS emprestimos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  family_id UUID NOT NULL, 
  descricao TEXT NOT NULL,
  valor_total NUMERIC(15, 2),
  valor_parcela NUMERIC(15, 2) NOT NULL,
  taxa_mensal_percentual NUMERIC(10, 4) NOT NULL, 
  total_parcelas INT NOT NULL,
  parcela_atual INT DEFAULT 1,
  data_primeiro_vencimento DATE NOT NULL,
  titular_id BIGINT REFERENCES titulares(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Add reference to emprestimo in despesas
ALTER TABLE despesas ADD COLUMN IF NOT EXISTS emprestimo_id BIGINT REFERENCES emprestimos(id);

-- 3. Enable RLS
ALTER TABLE emprestimos ENABLE ROW LEVEL SECURITY;

-- 4. Policies
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'emprestimos' 
        AND policyname = 'Users can manage loans of their own family'
    ) THEN
        CREATE POLICY "Users can manage loans of their own family" ON emprestimos
        FOR ALL
        USING (family_id IN (
            SELECT family_id FROM profiles WHERE id = auth.uid()
        ));
    END IF;
END $$;
