-- 0. EXTENSÕES E LIMPEZA TOTAL
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

DROP TABLE IF EXISTS public.receitas CASCADE;
DROP TABLE IF EXISTS public.despesas CASCADE;
DROP TABLE IF EXISTS public.cartoes CASCADE;
DROP TABLE IF EXISTS public.cartoes_config CASCADE;
DROP TABLE IF EXISTS public.emprestimos CASCADE;
DROP TABLE IF EXISTS public.contas_fixas CASCADE;
DROP TABLE IF EXISTS public.titulares CASCADE;
DROP TABLE IF EXISTS public.table_notas CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;
DROP TABLE IF EXISTS public.convites CASCADE;

-- 1. ESTRUTURA DE PERFIS E MULTI-TENANCY
CREATE TABLE public.profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    email TEXT,
    nome TEXT, 
    tipo TEXT NOT NULL DEFAULT 'membro',
    foto TEXT, 
    family_id UUID NOT NULL DEFAULT gen_random_uuid(), 
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE public.convites (
    id SERIAL PRIMARY KEY,
    family_id UUID NOT NULL,
    email TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 2. FUNÇÕES DE APOIO
CREATE OR REPLACE FUNCTION public.get_my_family_id()
RETURNS UUID AS $$
BEGIN
    RETURN (SELECT family_id FROM public.profiles WHERE id = auth.uid());
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 3. GATILHO PARA NOVOS USUÁRIOS
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
DECLARE
  target_family_id UUID;
BEGIN
  SELECT family_id INTO target_family_id FROM public.convites WHERE email = new.email;
  IF target_family_id IS NOT NULL THEN
    INSERT INTO public.profiles (id, email, family_id, nome, foto, tipo)
    VALUES (new.id, new.email, target_family_id, 
      COALESCE(new.raw_user_meta_data->>'display_name', new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1)),
      new.raw_user_meta_data->>'avatar_url', 'membro');
    DELETE FROM public.convites WHERE email = new.email;
  ELSE
    INSERT INTO public.profiles (id, email, family_id, nome, foto, tipo)
    VALUES (new.id, new.email, gen_random_uuid(), 
      COALESCE(new.raw_user_meta_data->>'display_name', new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1)),
      new.raw_user_meta_data->>'avatar_url', 'titular');
  END IF;
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 4. TABELAS DE NEGÓCIO (TITULARES E CONFIGURAÇÕES)
CREATE TABLE public.titulares (
    id SERIAL PRIMARY KEY,
    family_id UUID NOT NULL DEFAULT public.get_my_family_id(),
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    nome TEXT NOT NULL,
    foto TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE(family_id, nome)
);

CREATE TABLE public.cartoes_config (
    id SERIAL PRIMARY KEY,
    family_id UUID NOT NULL DEFAULT public.get_my_family_id(),
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    nome_cartao TEXT NOT NULL,
    titular_id INTEGER REFERENCES public.titulares(id) ON DELETE CASCADE,
    dia_vencimento INTEGER NOT NULL CHECK (dia_vencimento BETWEEN 1 AND 31),
    dia_fechamento INTEGER NOT NULL DEFAULT 7,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 5. MÓDULO DE EMPRÉSTIMOS E FINANCIAMENTOS
CREATE TABLE public.emprestimos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  family_id UUID NOT NULL DEFAULT public.get_my_family_id(), 
  descricao TEXT NOT NULL,
  valor_total NUMERIC(15, 2),
  valor_parcela NUMERIC(15, 2) NOT NULL,
  taxa_mensal_percentual NUMERIC(10, 4) NOT NULL, 
  taxa_anual_percentual NUMERIC(10, 4),
  total_parcelas INT NOT NULL,
  parcela_atual INT DEFAULT 1,
  data_primeiro_vencimento DATE NOT NULL,
  competencia_inicial TEXT,
  titular_id INTEGER REFERENCES public.titulares(id) ON DELETE SET NULL,
  saldo_devedor_atual NUMERIC(15, 2),
  valor_amortizacao_base NUMERIC(15, 2),
  indexador_mensal_estimado NUMERIC(10, 4) DEFAULT 0,
  seguros_taxas NUMERIC(15, 2) DEFAULT 0,
  valor_subsidio_fgts NUMERIC(15, 2) DEFAULT 0,
  meses_subsidio_restantes INT DEFAULT 0,
  fgts_mes_inicio TEXT,
  fgts_percentual_utilizado NUMERIC(10, 4),
  fgts_valor_total NUMERIC(15, 2),
  categoria TEXT CHECK (categoria IN ('Veículo', 'Imóvel')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. MÓDULO DE CONTAS FIXAS (VIRTUAIS)
CREATE TABLE public.contas_fixas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) NOT NULL,
    family_id UUID NOT NULL DEFAULT public.get_my_family_id(),
    descricao TEXT NOT NULL,
    valor_mensal NUMERIC(15, 2) NOT NULL,
    total_parcelas INTEGER, -- NULL indica sem prazo (indeterminado)
    parcela_atual INTEGER NOT NULL DEFAULT 1,
    data_inicio DATE NOT NULL,
    competencia_inicial TEXT NOT NULL,
    titular_id INTEGER REFERENCES public.titulares(id) ON DELETE SET NULL,
    categoria TEXT,
    tipo TEXT NOT NULL DEFAULT 'despesa' CHECK (tipo IN ('despesa', 'receita')),
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 7. TABELAS DE LANÇAMENTOS (SEM SIMULAÇÕES)
CREATE TABLE public.cartoes (
    id SERIAL PRIMARY KEY,
    family_id UUID NOT NULL DEFAULT public.get_my_family_id(),
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    cartao_id INTEGER REFERENCES public.cartoes_config(id) ON DELETE CASCADE,
    estabelecimento TEXT NOT NULL,
    categoria TEXT,
    titular_id INTEGER REFERENCES public.titulares(id) ON DELETE CASCADE,
    valor DECIMAL(12,2) NOT NULL,
    parcela_atual INTEGER DEFAULT 1,
    parcela_total INTEGER DEFAULT 1,
    data_compra DATE NOT NULL,
    competencia TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE public.despesas (
    id SERIAL PRIMARY KEY,
    family_id UUID NOT NULL DEFAULT public.get_my_family_id(),
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    emprestimo_id BIGINT REFERENCES public.emprestimos(id) ON DELETE SET NULL,
    conta_fixa_id BIGINT REFERENCES public.contas_fixas(id) ON DELETE SET NULL,
    descricao TEXT NOT NULL,
    categoria TEXT,
    valor DECIMAL(12,2) NOT NULL,
    parcela_atual INTEGER DEFAULT 1,
    parcela_total INTEGER DEFAULT 1,
    vencimento DATE NOT NULL,
    status TEXT NOT NULL DEFAULT 'Em aberto' CHECK (status IN ('Pago', 'Em aberto', 'Vencida', 'Hoje')),
    titular_id INTEGER REFERENCES public.titulares(id) ON DELETE CASCADE,
    competencia TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE public.receitas (
    id SERIAL PRIMARY KEY,
    family_id UUID NOT NULL DEFAULT public.get_my_family_id(),
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    descricao TEXT NOT NULL,
    categoria TEXT,
    valor DECIMAL(12,2) NOT NULL,
    parcela_atual INTEGER DEFAULT 1,
    parcela_total INTEGER DEFAULT 1,
    data_recebimento DATE NOT NULL,
    status TEXT NOT NULL DEFAULT 'Recebido' CHECK (status IN ('Recebido', 'Pendente')),
    titular_id INTEGER REFERENCES public.titulares(id) ON DELETE CASCADE,
    competencia TEXT NOT NULL,
    conta_fixa_id BIGINT REFERENCES public.contas_fixas(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE public.table_notas (
    family_id UUID PRIMARY KEY DEFAULT public.get_my_family_id(),
    conteudo TEXT,
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 8. SEGURANÇA (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.convites ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.titulares ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cartoes_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cartoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.despesas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.receitas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.table_notas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.emprestimos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contas_fixas ENABLE ROW LEVEL SECURITY;

-- Políticas de Acesso
DO $$ 
DECLARE 
    tab TEXT;
BEGIN
    FOR tab IN SELECT table_name FROM information_schema.tables 
               WHERE table_schema = 'public' AND table_name IN ('titulares', 'cartoes_config', 'cartoes', 'despesas', 'receitas', 'table_notas', 'emprestimos', 'convites', 'contas_fixas')
    LOOP
        EXECUTE format('DROP POLICY IF EXISTS "Acesso por Família" ON public.%I', tab);
        EXECUTE format('CREATE POLICY "Acesso por Família" ON public.%I FOR ALL USING (family_id = get_my_family_id()) WITH CHECK (family_id = get_my_family_id())', tab);
    END LOOP;
END $$;

CREATE POLICY "Leitura de perfis da família" ON public.profiles FOR SELECT USING (id = auth.uid() OR family_id = public.get_my_family_id());
CREATE POLICY "Permitir inserção do próprio perfil" ON public.profiles FOR INSERT WITH CHECK (id = auth.uid());
CREATE POLICY "Atualização do próprio perfil" ON public.profiles FOR UPDATE USING (id = auth.uid());
CREATE POLICY "Exclusão do próprio perfil" ON public.profiles FOR DELETE USING (id = auth.uid());

-- 9. GATILHOS E UTILITÁRIOS
CREATE OR REPLACE FUNCTION public.handle_updated_at() RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER tr_despesas_updated_at BEFORE UPDATE ON public.despesas FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();
CREATE TRIGGER tr_receitas_updated_at BEFORE UPDATE ON public.receitas FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();
CREATE TRIGGER tr_notas_updated_at BEFORE UPDATE ON public.table_notas FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();
CREATE TRIGGER tr_contas_fixas_updated_at BEFORE UPDATE ON public.contas_fixas FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

-- 10. ÍNDICES DE PERFORMANCE
CREATE INDEX IF NOT EXISTS idx_despesas_family_id ON public.despesas(family_id);
CREATE INDEX IF NOT EXISTS idx_despesas_vencimento ON public.despesas(vencimento);
CREATE INDEX IF NOT EXISTS idx_despesas_status ON public.despesas(status);
CREATE INDEX IF NOT EXISTS idx_despesas_conta_fixa_id ON public.despesas(conta_fixa_id);
CREATE INDEX IF NOT EXISTS idx_receitas_family_id ON public.receitas(family_id);
CREATE INDEX IF NOT EXISTS idx_cartoes_family_id ON public.cartoes(family_id);
CREATE INDEX IF NOT EXISTS idx_contas_fixas_family_id ON public.contas_fixas(family_id);
CREATE INDEX IF NOT EXISTS idx_receitas_conta_fixa_id ON public.receitas(conta_fixa_id);
